services:
  statimg:
    container_name: statimg
    image: 404e/statimg:1.3.0
    env_file:
      - .env
    volumes:
      - ./font:/app/font # 字体文件夹
      - /dev/null:/app/logs # 禁用日志
    restart: unless-stopped
    ports:
      - "80:80" # 绑定宿主机端口
